default_platform(:ios)

platform :ios do
  lane :build_game do |options|
    cocoapods
    build_app(
      export_method: "app-store",
      export_xcargs: "-allowProvisioningUpdates"
    )
  end
  lane :upload_game do |options|
    cocoapods
    build_app(
      export_method: "app-store",
      export_xcargs: "-allowProvisioningUpdates"
    )
    upload_to_testflight
  end
end
